[theme]
primaryColor="#F63366"
backgroundColor="#0E1117"  # Um cinza muito escuro
secondaryBackgroundColor="#262730"  # Um cinza escuro para contrastar com o background
textColor="#FFFFFF"  # Branco para o texto
font="sans serif"
